# Generated by Django 3.1.4 on 2020-12-28 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('video', models.BooleanField(default=False)),
                ('audio', models.BooleanField(default=False)),
                ('video_codec', models.CharField(choices=[('libx264', 'H264'), ('libx265', 'HEVC')], max_length=32)),
                ('video_vresolution', models.CharField(choices=[('qvga', 'QVGA (320x240)'), ('vga', 'VGA (640x480)'), ('ntsc', 'NTSC (720x480)'), ('pal', 'PAL (720x576)'), ('hd480', '480P (852x480)'), ('hd720', '720P (1280x720)'), ('hd1080', '1080P (1920x1080)'), ('2k', '2K (2048x1080)'), ('4k', '4K (4096x2160)')], max_length=32)),
                ('video_bitrate', models.PositiveIntegerField(default=0)),
                ('video_framerate', models.PositiveIntegerField(default=0)),
                ('advanced_video_encoding', models.BooleanField(default=False)),
                ('cbr', models.BooleanField(default=False)),
                ('video_min_bitrate', models.PositiveIntegerField()),
                ('video_max_bitrate', models.PositiveIntegerField()),
                ('video_preset', models.CharField(choices=[('ultrafast', 'Ultrafast'), ('superfast', 'Superfast'), ('veryfast', 'Veryfast'), ('faster', 'Faster'), ('fast', 'Fast'), ('medium', 'Medium'), ('slow', 'Slow'), ('slower', 'Slower'), ('veryslow', 'Veryslow')], default='medium', max_length=32)),
                ('video_profile', models.CharField(choices=[('baseline', 'Baseline'), ('main', 'Main'), ('high', 'High'), ('high10', 'High10'), ('high422', 'High422'), ('high444', 'High444')], default='main', max_length=32)),
                ('video_buffer', models.PositiveIntegerField(null=True)),
                ('video_gop', models.PositiveIntegerField(null=True)),
                ('video_kyeframe_interval', models.PositiveIntegerField(null=True)),
                ('enable_deinterlace', models.BooleanField(default=False)),
                ('enable_zero_latency', models.BooleanField(default=False)),
                ('audio_codec', models.CharField(choices=[('aac', 'AAC'), ('libopus', 'Libopus')], default='aac', max_length=32)),
                ('audio_channels', models.CharField(choices=[('1', 'Mono'), ('2', 'Stereo')], default='2', max_length=32)),
                ('audio_bitrate', models.CharField(choices=[('64', '64'), ('96', '96'), ('128', '128'), ('144', '144'), ('160', '160'), ('192', '192'), ('256', '256')], default='144', max_length=32)),
                ('audio_sample_rate', models.CharField(choices=[('44100', '44.1 khz'), ('48000', '48 khz'), ('88200', '88.2 khz'), ('96000', '96 khz'), ('192000', '192 khz')], default='44100', max_length=32)),
                ('advanced_audio_encoding', models.BooleanField(default=False)),
                ('audio_gain', models.CharField(choices=[('-20db', '-20db'), ('-10db', '-10db'), ('0db', '0db'), ('10db', '10db'), ('20db', '20db')], default='0db', max_length=32)),
                ('audio_delay', models.IntegerField(default=0)),
            ],
        ),
    ]
